export const ProductActionTypes = {
    FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",
    FETCH_PRODUCT_LOADING: "FETCH_PRODUCT_LOADING",
    FETCH_PRODUCT_ERROR: "FETCH_PRODUCT_ERROR",
    REMOVE_PRODUCT: "REMOVE_PRODUCT",
};
