const CartActionTypes = {
    ADD_ITEM: "ADD_ITEM",
    SUBMIT_ITEMS_SUCCESS: "SUBMIT_ITEMS_SUCCESS",
    SUBMIT_ITEMS_LOADING: "SUBMIT_ITEMS_LOADING",
    SUBMIT_ITEMS_ERROR: "SUBMIT_ITEMS_ERROR",
    CLEAR_ITEMS: "CLEAR_ITEMS",
};

export default CartActionTypes;
